// Fuzzy team-name matching for the multi-rating-system pulls — the
// published Google Sheet, the McIllece CSV, and the Massey CSV each use
// their own slightly different team naming (Texas St vs Texas State, Miami
// FL vs Miami, San Jose State vs San José State, UConn vs Connecticut,
// etc). This maps any of those onto this site's canonical TEAMS_BY_NAME
// keys, falling back to a normalized/alias match, then a nearest-match
// suggestion — never a silent guess past that point. Callers should show
// unmatched names to the admin for manual review (same pattern as Monte
// Carlo's unmatchedTeams handling).

import { TEAMS, TEAMS_BY_NAME } from "../data/teams";

// Hand-maintained aliases for names that show up across these specific
// sources and don't normalize cleanly on their own. Keyed by normalized
// form (see normalize()) -> canonical team name from data/teams.ts.
//
// The block below the original ~182 entries (marked below) was generated
// by testing 855 real-world name variants pulled from multiple outside
// sources (ESPN, TeamRankings, KFord, PFF, BCF, Massey, and a hand-curated
// team/mascot database) against the ACTUAL matching logic in this file,
// keeping only the ones that didn't already resolve correctly. One
// dangerous fuzzy-match false positive was found and fixed in the
// process: "SC State" was matching "NC State" (wrong school entirely) —
// now has an explicit alias overriding that.
const ALIASES: Record<string, string> = {
  "ohio st": "Ohio State",
  "penn st": "Penn State",
  "miami fl": "Miami",
  "iowa st": "Iowa State",
  "texas st": "Texas State",
  "texas tech": "Texas Tech",
  "kansas st": "Kansas State",
  "arizona st": "Arizona State",
  "michigan st": "Michigan State",
  "mississippi st": "Mississippi State",
  "mississippi": "Ole Miss",
  "ole miss": "Ole Miss",
  "boise st": "Boise State",
  "fresno st": "Fresno State",
  "san diego st": "San Diego State",
  "sam houston st": "Sam Houston",
  "utah st": "Utah State",
  "washington st": "Washington State",
  "oregon st": "Oregon State",
  "colorado st": "Colorado State",
  "oklahoma st": "Oklahoma State",
  "florida st": "Florida State",
  "new mexico st": "New Mexico State",
  "jacksonville st": "Jacksonville State",
  "georgia st": "Georgia State",
  "kennesaw st": "Kennesaw State",
  "kennesaw": "Kennesaw State",
  "ga southern": "Georgia Southern",
  "app state": "App State",
  "appalachian st": "App State",
  "appalachian state": "App State",
  "coastal car": "Coastal Carolina",
  "cent michigan": "Central Michigan",
  "c michigan": "Central Michigan",
  "e michigan": "Eastern Michigan",
  "w michigan": "Western Michigan",
  "wku": "Western Kentucky",
  "mtsu": "Middle Tennessee",
  "middle tenn": "Middle Tennessee",
  "ul monroe": "UL Monroe",
  "louisiana monroe": "UL Monroe",
  "ulm": "UL Monroe",
  "louisiana": "Louisiana",
  "ul lafayette": "Louisiana",
  "fl atlantic": "Florida Atlantic",
  "florida intl": "Florida International",
  "florida international": "Florida International",
  "fiu": "Florida International",
  "san jose st": "San José State",
  "san josé st": "San José State",
  "san jose state": "San José State",
  "uconn": "UConn",
  "connecticut": "UConn",
  "hawaii": "Hawai'i",
  "hawai i": "Hawai'i",
  "utsa": "UTSA",
  "ut san antonio": "UTSA",
  "utep": "UTEP",
  "unlv": "UNLV",
  "ul monroe warhawks": "UL Monroe",
  "n illinois": "Northern Illinois",
  "n dakota st": "North Dakota State",
  "north dakota st": "North Dakota State",
  "s dakota st": "South Dakota State",
  "south dakota st": "South Dakota State",
  "e carolina": "East Carolina",
  "s florida": "South Florida",
  "south fl": "South Florida",
  "usf": "South Florida",
  "ucf": "UCF",
  "central florida": "UCF",
  "byu": "BYU",
  "smu": "SMU",
  "tcu": "TCU",
  "lsu": "LSU",
  "usc": "USC",
  "ucla": "UCLA",
  "nc state": "NC State",
  "n carolina": "North Carolina",
  "unc": "North Carolina",
  "virginia tech": "Virginia Tech",
  "vt": "Virginia Tech",
  "ga tech": "Georgia Tech",
  "georgia tech": "Georgia Tech",
  "old dominion": "Old Dominion",
  "fau": "Florida Atlantic",
  "james madison": "James Madison",
  "jmu": "James Madison",
  "n texas": "North Texas",
  "north texas": "North Texas",
  "s alabama": "South Alabama",
  "south alabama": "South Alabama",
  "arkansas st": "Arkansas State",
  "sacramento st": "Sacramento State",
  "cs sacramento": "Sacramento State",
  "sac state": "Sacramento State",
  "montana st": "Montana State",
  "n dakota": "North Dakota",
  "north dakota": "North Dakota",
  "s dakota": "South Dakota",
  "south dakota": "South Dakota",
  "s illinois": "Southern Illinois",
  "southern illinois": "Southern Illinois",
  "illinois st": "Illinois State",
  "tarleton st": "Tarleton State",
  "abilene chr": "Abilene Christian",
  "sf austin": "Stephen F. Austin",
  "stephen f austin": "Stephen F. Austin",
  "uc davis": "UC Davis",
  "uab": "UAB",
  "gardner webb": "Gardner-Webb",
  "monmouth nj": "Monmouth",
  "w carolina": "Western Carolina",
  "cal poly": "Cal Poly",
  "cent arkansas": "Central Arkansas",
  "central conn": "Central Connecticut",
  "ccsu": "Central Connecticut",
  "e kentucky": "Eastern Kentucky",
  "e washington": "Eastern Washington",
  "tn martin": "UT Martin",
  "ut martin": "UT Martin",
  "n arizona": "Northern Arizona",
  "northern arizona": "Northern Arizona",
  "e illinois": "Eastern Illinois",
  "w illinois": "Western Illinois",
  "st thomas mn": "St. Thomas (MN)",
  "st thomas": "St. Thomas (MN)",
  "n colorado": "Northern Colorado",
  "northern colorado": "Northern Colorado",
  "se missouri st": "Southeast Missouri State",
  "se louisiana": "SE Louisiana",
  "charleston so": "Charleston Southern",
  "west florida": "West Florida",
  "prairie view": "Prairie View A&M",
  "nc central": "North Carolina Central",
  "north carolina central": "North Carolina Central",
  "tx southern": "Texas Southern",
  "texas southern": "Texas Southern",
  "ark pine bluff": "Arkansas-Pine Bluff",
  "arkansas pine bluff": "Arkansas-Pine Bluff",
  "houston chr": "Houston Christian",
  "houston christian": "Houston Christian",
  "ms valley st": "Mississippi Valley State",
  "mississippi valley st": "Mississippi Valley State",
  "miss valley state": "Mississippi Valley State",
  "liu post": "Long Island University",
  "liu": "Long Island University",
  "long island university": "Long Island University",
  "sacred heart": "Sacred Heart",
  "chicago st": "Chicago State",
  "utrgv": "UT Rio Grande Valley",
  "ut rio grande valley": "UT Rio Grande Valley",
  "suny albany": "UAlbany",
  "albany": "UAlbany",
  "citadel": "The Citadel",
  "the citadel": "The Citadel",
  "william and mary": "William & Mary",
  "penn": "Pennsylvania",
  "pennsylvania": "Pennsylvania",
  "mcneese st": "McNeese",
  "mcneese": "McNeese",
  "mcneese state": "McNeese",
  "nicholls st": "Nicholls",
  "nicholls": "Nicholls",
  "nicholls state": "Nicholls",
  "cal": "California",
  "etsu": "East Tennessee State",
  "se missouri state": "Southeast Missouri State",
  "northwestern la": "Northwestern State",
  "pitt": "Pittsburgh",
  "jax state": "Jacksonville State",
  "umass": "Massachusetts",
  "stonehill college": "Stonehill",
  "southern university": "Southern",
  "southern univ": "Southern",
  "kent": "Kent State",
  "miami oh": "Miami (OH)",
  "nc a and t": "North Carolina A&T",
  "north carolina a and t": "North Carolina A&T",
  "east texas a and m": "East Texas A&M",
  "prairie view a and m": "Prairie View A&M",
  "alabama a and m": "Alabama A&M",

  // --- Generated from real-world source data (855 variants tested,
  // 485 already worked, 522 new entries below) ---
"afa": "Air Force",
  "afaair force": "Air Force",
  "afaair force falcons": "Air Force",
  "air force falcons afa": "Air Force",
  "akr": "Akron",
  "akrakron": "Akron",
  "akrakron zips": "Akron",
  "akron zips akr": "Akron",
  "ala": "Alabama",
  "alaalabama": "Alabama",
  "alaalabama crimson tide": "Alabama",
  "alabama crimson tide ala": "Alabama",
  "alabama-birmingham blazers uab": "UAB",
  "albany-ny": "UAlbany",
  "app": "App State",
  "appalachian state mountaineers app": "App State",
  "appappalachian state": "App State",
  "appappalachian state mountaineers": "App State",
  "ariz": "Arizona",
  "arizarizona": "Arizona",
  "arizarizona wildcats": "Arizona",
  "arizona state sun devils asu": "Arizona State",
  "arizona wildcats ariz": "Arizona",
  "ark": "Arkansas",
  "ark-pine bluff": "Arkansas-Pine Bluff",
  "arkansas razorbacks ark": "Arkansas",
  "arkansas state red wolves arst": "Arkansas State",
  "arkarkansas": "Arkansas",
  "arkarkansas razorbacks": "Arkansas",
  "army black knights army": "Army",
  "army west point": "Army",
  "armyarmy": "Army",
  "armyarmy black knights": "Army",
  "arst": "Arkansas State",
  "arstarkansas state": "Arkansas State",
  "arstarkansas state red wolves": "Arkansas State",
  "asu": "Arizona State",
  "asuarizona state": "Arizona State",
  "asuarizona state sun devils": "Arizona State",
  "aub": "Auburn",
  "aubauburn": "Auburn",
  "aubauburn tigers": "Auburn",
  "auburn tigers aub": "Auburn",
  "b y u": "BYU",
  "ball": "Ball State",
  "ball state cardinals ball": "Ball State",
  "ballball state": "Ball State",
  "ballball state cardinals": "Ball State",
  "bay": "Baylor",
  "baybaylor": "Baylor",
  "baybaylor bears": "Baylor",
  "baylor bears bay": "Baylor",
  "bc": "Boston College",
  "bcboston college eagles": "Boston College",
  "bgsu": "Bowling Green",
  "bgsubowling green": "Bowling Green",
  "bgsubowling green falcons": "Bowling Green",
  "boisboise state": "Boise State",
  "boisboise state broncos": "Boise State",
  "boise state broncos bsu": "Boise State",
  "boston col": "Boston College",
  "boston coll": "Boston College",
  "boston college eagles bc": "Boston College",
  "bowling green state falcons bgsu": "Bowling Green",
  "bowling grn": "Bowling Green",
  "brigham young": "BYU",
  "brigham young cougars byu": "BYU",
  "bryant university": "Bryant",
  "bsu": "Boise State",
  "buff": "Buffalo",
  "buffalo bulls buff": "Buffalo",
  "buffbuffalo": "Buffalo",
  "buffbuffalo bulls": "Buffalo",
  "byubyu": "BYU",
  "byubyu cougars": "BYU",
  "c conn st": "Central Connecticut",
  "cal poly-slo": "Cal Poly",
  "calcalifornia": "California",
  "calcalifornia golden bears": "California",
  "california golden bears cal": "California",
  "ccu": "Coastal Carolina",
  "ccucoastal carolina": "Coastal Carolina",
  "ccucoastal carolina chanticleers": "Coastal Carolina",
  "central florida knights ucf": "UCF",
  "central florida(ucf)": "UCF",
  "central mich": "Central Michigan",
  "central michigan chippewas cmu": "Central Michigan",
  "charlotte 49ers char": "Charlotte",
  "cin": "Cincinnati",
  "cincincinnati": "Cincinnati",
  "cincincinnati bearcats": "Cincinnati",
  "cincinnati bearcats cin": "Cincinnati",
  "clem": "Clemson",
  "clemclemson": "Clemson",
  "clemclemson tigers": "Clemson",
  "clemson tigers clem": "Clemson",
  "cltcharlotte": "Charlotte",
  "cltcharlotte ers": "Charlotte",
  "cmu": "Central Michigan",
  "cmucentral michigan": "Central Michigan",
  "cmucentral michigan chippewas": "Central Michigan",
  "coastal caro": "Coastal Carolina",
  "coastal carolina chanticleers ccu": "Coastal Carolina",
  "colo": "Colorado",
  "colocolorado": "Colorado",
  "colocolorado buffaloes": "Colorado",
  "colorado buffaloes colo": "Colorado",
  "colorado state rams csu": "Colorado State",
  "conn": "UConn",
  "connecticut huskies": "UConn",
  "csu": "Colorado State",
  "csucolorado state": "Colorado State",
  "csucolorado state rams": "Colorado State",
  "duke blue devils": "Duke",
  "east carolina pirates": "East Carolina",
  "eastern mich": "Eastern Michigan",
  "eastern michigan eagles": "Eastern Michigan",
  "ecu": "East Carolina",
  "emu": "Eastern Michigan",
  "fla": "Florida",
  "fla international": "Florida International",
  "florida atlantic owls": "Florida Atlantic",
  "florida gators": "Florida",
  "florida international panthers": "Florida International",
  "florida state seminoles": "Florida State",
  "fres": "Fresno State",
  "fresno state bulldogs": "Fresno State",
  "fsu": "Florida State",
  "gaso": "Georgia Southern",
  "gast": "Georgia State",
  "georgia bulldogs": "Georgia",
  "georgia southern eagles": "Georgia Southern",
  "georgia state panthers": "Georgia State",
  "georgia tech yellow jackets": "Georgia Tech",
  "grambling st": "Grambling",
  "grambling state": "Grambling",
  "gt": "Georgia Tech",
  "haw": "Hawai'i",
  "hawaii rainbow warriors": "Hawai'i",
  "hawaii warriors": "Hawai'i",
  "hou": "Houston",
  "houston cougars": "Houston",
  "ill": "Illinois",
  "illinois fighting illini": "Illinois",
  "ind": "Indiana",
  "indiana hoosiers": "Indiana",
  "iowa hawkeyes": "Iowa",
  "iowa state cyclones": "Iowa State",
  "isu": "Iowa State",
  "jacksonville state gamecocks": "Jacksonville State",
  "james mad": "James Madison",
  "james madison dukes": "James Madison",
  "jville st": "Jacksonville State",
  "jvst": "Jacksonville State",
  "kansas jayhawks": "Kansas",
  "kansas state wildcats": "Kansas State",
  "kenn": "Kennesaw State",
  "kennesaw state owls": "Kennesaw State",
  "kent state golden flashes": "Kent State",
  "kentucky wildcats uk": "Kentucky",
  "ksu": "Kansas State",
  "ku": "Kansas",
  "l s u": "LSU",
  "la tech": "Louisiana Tech",
  "lib": "Liberty",
  "liberty flames lib": "Liberty",
  "libliberty": "Liberty",
  "libliberty flames": "Liberty",
  "long island": "Long Island University",
  "louisiana state tigers lsu": "LSU",
  "louisiana tech bulldogs lt": "Louisiana Tech",
  "louisiana-lafayette": "Louisiana",
  "louisiana-lafayette ragin cajuns ull": "Louisiana",
  "louisiana-monroe": "UL Monroe",
  "louisiana-monroe warhawks ulm": "UL Monroe",
  "loulouisville": "Louisville",
  "loulouisville cardinals": "Louisville",
  "lsu tigers": "LSU",
  "lsulsu": "LSU",
  "lsulsu tigers": "LSU",
  "lt": "Louisiana Tech",
  "ltlouisiana tech bulldogs": "Louisiana Tech",
  "m t s u": "Middle Tennessee",
  "m-ohmiami (oh)": "Miami (OH)",
  "m-ohmiami (oh) redhawks": "Miami (OH)",
  "marshall thundering herd mrsh": "Marshall",
  "maryland terrapins md": "Maryland",
  "massachusetts minutemen mass": "Massachusetts",
  "massmassachusetts": "Massachusetts",
  "massmassachusetts minutemen": "Massachusetts",
  "md": "Maryland",
  "mdmaryland": "Maryland",
  "mdmaryland terrapins": "Maryland",
  "memmemphis": "Memphis",
  "memmemphis tigers": "Memphis",
  "memphis tigers mem": "Memphis",
  "miami (fl)": "Miami",
  "miami (fl) hurricanes mia": "Miami",
  "miami (fla)": "Miami",
  "miami (ohio)": "Miami (OH)",
  "miami hurricanes": "Miami",
  "miami-fl": "Miami",
  "miami-florida": "Miami",
  "miami-oh": "Miami (OH)",
  "miami-ohio": "Miami (OH)",
  "miamiami": "Miami",
  "miamiami hurricanes": "Miami",
  "mich": "Michigan",
  "michigan state spartans msu": "Michigan State",
  "michigan wolverines mich": "Michigan",
  "michmichigan": "Michigan",
  "michmichigan wolverines": "Michigan",
  "middle tennessee state blue raiders mtu": "Middle Tennessee",
  "minn": "Minnesota",
  "minnesota golden gophers minn": "Minnesota",
  "minnminnesota": "Minnesota",
  "minnminnesota golden gophers": "Minnesota",
  "miss": "Ole Miss",
  "miss st": "Mississippi State",
  "miss state": "Mississippi State",
  "mississippi rebels miss": "Ole Miss",
  "mississippi state bulldogs msst": "Mississippi State",
  "missole miss": "Ole Miss",
  "missole miss rebels": "Ole Miss",
  "missouri tigers mizz": "Missouri",
  "miz": "Missouri",
  "mizmissouri": "Missouri",
  "mizmissouri tigers": "Missouri",
  "monmouth-nj": "Monmouth",
  "mrshmarshall": "Marshall",
  "mrshmarshall thundering herd": "Marshall",
  "ms valley": "Mississippi Valley State",
  "msst": "Mississippi State",
  "msstmississippi state": "Mississippi State",
  "msstmississippi state bulldogs": "Mississippi State",
  "msu": "Michigan State",
  "msumichigan state": "Michigan State",
  "msumichigan state spartans": "Michigan State",
  "mtsumiddle tennessee": "Middle Tennessee",
  "mtsumiddle tennessee blue raiders": "Middle Tennessee",
  "n mex state": "New Mexico State",
  "navy midshipmen navy": "Navy",
  "navynavy": "Navy",
  "navynavy midshipmen": "Navy",
  "ncst": "NC State",
  "ncsunc state": "NC State",
  "ncsunc state wolfpack": "NC State",
  "nd": "Notre Dame",
  "ndnotre dame": "Notre Dame",
  "ndnotre dame fighting irish": "Notre Dame",
  "neb": "Nebraska",
  "nebnebraska": "Nebraska",
  "nebnebraska cornhuskers": "Nebraska",
  "nebraska cornhuskers neb": "Nebraska",
  "nev": "Nevada",
  "nevada wolf pack nev": "Nevada",
  "nevada-las vegas rebels unlv": "UNLV",
  "nevnevada": "Nevada",
  "nevnevada wolf pack": "Nevada",
  "new mexico lobos unm": "New Mexico",
  "new mexico state aggies nmsu": "New Mexico State",
  "niu": "Northern Illinois",
  "niunorthern illinois huskies": "Northern Illinois",
  "nmsu": "New Mexico State",
  "nmsunew mexico state": "New Mexico State",
  "nmsunew mexico state aggies": "New Mexico State",
  "norfolk": "Norfolk State",
  "north carolina state wolfpack ncst": "NC State",
  "north carolina tar heels unc": "North Carolina",
  "north texas mean green unt": "North Texas",
  "northern ill": "Northern Illinois",
  "northern illinois huskies niu": "Northern Illinois",
  "northwestern wildcats nw": "Northwestern",
  "notre dame fighting irish nd": "Notre Dame",
  "nunorthwestern wildcats": "Northwestern",
  "nw": "Northwestern",
  "odu": "Old Dominion",
  "oduold dominion": "Old Dominion",
  "oduold dominion monarchs": "Old Dominion",
  "ohio bobcats ohio": "Ohio",
  "ohio state buckeyes osu": "Ohio State",
  "ohioohio": "Ohio",
  "ohioohio bobcats": "Ohio",
  "okla": "Oklahoma",
  "oklahoma sooners okla": "Oklahoma",
  "oklahoma state cowboys okst": "Oklahoma State",
  "okst": "Oklahoma State",
  "okstoklahoma state": "Oklahoma State",
  "okstoklahoma state cowboys": "Oklahoma State",
  "old dominion monarchs odu": "Old Dominion",
  "ore": "Oregon",
  "oregon ducks ore": "Oregon",
  "oregon state beavers orst": "Oregon State",
  "oreoregon": "Oregon",
  "oreoregon ducks": "Oregon",
  "orst": "Oregon State",
  "orstoregon state": "Oregon State",
  "orstoregon state beavers": "Oregon State",
  "osu": "Ohio State",
  "osuohio state": "Ohio State",
  "osuohio state buckeyes": "Ohio State",
  "ouoklahoma": "Oklahoma",
  "ouoklahoma sooners": "Oklahoma",
  "pc": "Presbyterian",
  "penn state nittany lions psu": "Penn State",
  "pittpittsburgh": "Pittsburgh",
  "pittpittsburgh panthers": "Pittsburgh",
  "pittsburgh panthers pitt": "Pittsburgh",
  "presbyterian college": "Presbyterian",
  "psu": "Penn State",
  "psupenn state": "Penn State",
  "psupenn state nittany lions": "Penn State",
  "purdue boilermakers pur": "Purdue",
  "purpurdue": "Purdue",
  "purpurdue boilermakers": "Purdue",
  "rice owls rice": "Rice",
  "ricerice": "Rice",
  "ricerice owls": "Rice",
  "rutgers scarlet knights rutg": "Rutgers",
  "rutgrutgers": "Rutgers",
  "rutgrutgers scarlet knights": "Rutgers",
  "s methodist": "SMU",
  "s mississippi": "Southern Miss",
  "sam hous st": "Sam Houston",
  "sam houston state": "Sam Houston",
  "sam houston state bearkats shsu": "Sam Houston",
  "san diego state aztecs sdsu": "San Diego State",
  "san jose state spartans sjsu": "San José State",
  "sc st": "South Carolina State",
  "sc state": "South Carolina State",
  "scsouth carolina gamecocks": "South Carolina",
  "sdsu": "San Diego State",
  "sdsusan diego state": "San Diego State",
  "sdsusan diego state aztecs": "San Diego State",
  "semo": "Southeast Missouri State",
  "shsu": "Sam Houston",
  "shsusam houston bearkats": "Sam Houston",
  "shsusam houston state": "Sam Houston",
  "sjsu": "San José State",
  "sjsusan jose state": "San José State",
  "sjsusan jose state spartans": "San José State",
  "smusmu": "SMU",
  "smusmu mustangs": "SMU",
  "so miss": "Southern Miss",
  "south alabama jaguars soal": "South Alabama",
  "south carolina gamecocks scar": "South Carolina",
  "south florida bulls usf": "South Florida",
  "southeast missouri": "Southeast Missouri State",
  "southeastern la": "SE Louisiana",
  "southeastern louisiana": "SE Louisiana",
  "southern california trojans usc": "USC",
  "southern methodist mustangs smu": "SMU",
  "southern mississippi": "Southern Miss",
  "southern mississippi golden eagles usm": "Southern Miss",
  "southern u": "Southern",
  "st thomas-mn": "St. Thomas (MN)",
  "stan": "Stanford",
  "stanford cardinal stan": "Stanford",
  "stanstanford": "Stanford",
  "stanstanford cardinal": "Stanford",
  "syr": "Syracuse",
  "syracuse orange syr": "Syracuse",
  "syrsyracuse": "Syracuse",
  "syrsyracuse orange": "Syracuse",
  "t c u": "TCU",
  "ta and m": "Texas A&M",
  "ta and mtexas a and m": "Texas A&M",
  "ta and mtexas a and m aggies": "Texas A&M",
  "tcu horned frogs": "TCU",
  "tcutcu": "TCU",
  "tcutcu horned frogs": "TCU",
  "tem": "Temple",
  "temple owls tem": "Temple",
  "temtemple": "Temple",
  "temtemple owls": "Temple",
  "tennessee volunteers tenn": "Tennessee",
  "tennessee-martin": "UT Martin",
  "tenntennessee": "Tennessee",
  "tenntennessee volunteers": "Tennessee",
  "tex": "Texas",
  "texas a and m aggies ta and m": "Texas A&M",
  "texas a and m-commerce": "East Texas A&M",
  "texas christian horned frogs tcu": "TCU",
  "texas longhorns tex": "Texas",
  "texas state bobcats txst": "Texas State",
  "texas tech red raiders ttu": "Texas Tech",
  "texas-el paso miners utep": "UTEP",
  "texas-san antonio roadrunners utsa": "UTSA",
  "textexas": "Texas",
  "textexas longhorns": "Texas",
  "tlsa": "Tulsa",
  "tlsatulsa": "Tulsa",
  "tlsatulsa golden hurricane": "Tulsa",
  "tol": "Toledo",
  "toledo rockets tol": "Toledo",
  "toltoledo": "Toledo",
  "toltoledo rockets": "Toledo",
  "troy trojans troy": "Troy",
  "troytroy": "Troy",
  "troytroy trojans": "Troy",
  "ttu": "Texas Tech",
  "ttutexas tech": "Texas Tech",
  "ttutexas tech red raiders": "Texas Tech",
  "tulane green wave tuln": "Tulane",
  "tuln": "Tulane",
  "tulntulane": "Tulane",
  "tulntulane green wave": "Tulane",
  "tulsa golden hurricane tlsa": "Tulsa",
  "tx a and m commerce": "East Texas A&M",
  "tx christian": "TCU",
  "tx el paso": "UTEP",
  "txst": "Texas State",
  "txsttexas state": "Texas State",
  "txsttexas state bobcats": "Texas State",
  "u a b": "UAB",
  "u c f": "UCF",
  "u c l a": "UCLA",
  "u l m": "UL Monroe",
  "u mass": "Massachusetts",
  "u n l v": "UNLV",
  "u s c": "USC",
  "u t e p": "UTEP",
  "uabuab": "UAB",
  "uabuab blazers": "UAB",
  "uapb": "Arkansas-Pine Bluff",
  "ucfucf": "UCF",
  "ucfucf knights": "UCF",
  "ucla bruins ucla": "UCLA",
  "uclaucla": "UCLA",
  "uclaucla bruins": "UCLA",
  "uconn huskies": "UConn",
  "uga": "Georgia",
  "uk": "Kentucky",
  "ukkentucky": "Kentucky",
  "ukkentucky wildcats": "Kentucky",
  "ul-lafayette": "Louisiana",
  "ull": "Louisiana",
  "ullouisiana": "Louisiana",
  "ullouisiana ragin cajuns": "Louisiana",
  "ulmul monroe": "UL Monroe",
  "ulmul monroe warhawks": "UL Monroe",
  "uncnorth carolina": "North Carolina",
  "uncnorth carolina tar heels": "North Carolina",
  "unlvunlv": "UNLV",
  "unlvunlv rebels": "UNLV",
  "unm": "New Mexico",
  "unmnew mexico": "New Mexico",
  "unmnew mexico lobos": "New Mexico",
  "unt": "North Texas",
  "untnorth texas": "North Texas",
  "untnorth texas mean green": "North Texas",
  "usa": "South Alabama",
  "usasouth alabama": "South Alabama",
  "usasouth alabama jaguars": "South Alabama",
  "uscusc": "USC",
  "uscusc trojans": "USC",
  "usfsouth florida": "South Florida",
  "usfsouth florida bulls": "South Florida",
  "usmsouthern miss": "Southern Miss",
  "usmsouthern miss golden eagles": "Southern Miss",
  "usu": "Utah State",
  "usuutah state": "Utah State",
  "usuutah state aggies": "Utah State",
  "utah state aggies usu": "Utah State",
  "utah tech trailblazers": "Utah Tech",
  "utah utes utah": "Utah",
  "utahutah": "Utah",
  "utahutah utes": "Utah",
  "uteputep": "UTEP",
  "uteputep miners": "UTEP",
  "utsautsa": "UTSA",
  "utsautsa roadrunners": "UTSA",
  "uva": "Virginia",
  "uvavirginia": "Virginia",
  "uvavirginia cavaliers": "Virginia",
  "v m i": "VMI",
  "va tech": "Virginia Tech",
  "van": "Vanderbilt",
  "vanderbilt commodores van": "Vanderbilt",
  "vanvanderbilt": "Vanderbilt",
  "vanvanderbilt commodores": "Vanderbilt",
  "virginia cavaliers uva": "Virginia",
  "virginia military institute": "VMI",
  "virginia tech hokies vt": "Virginia Tech",
  "vtvirginia tech hokies": "Virginia Tech",
  "w k u": "Western Kentucky",
  "w kentucky": "Western Kentucky",
  "wake": "Wake Forest",
  "wake forest demon deacons wake": "Wake Forest",
  "wakewake": "Wake Forest",
  "wakewake forest demon deacons": "Wake Forest",
  "wash": "Washington",
  "wash state": "Washington State",
  "washington huskies wash": "Washington",
  "washington state cougars wsu": "Washington State",
  "washwashington": "Washington",
  "washwashington huskies": "Washington",
  "weber": "Weber State",
  "west va": "West Virginia",
  "west virginia mountaineers wvu": "West Virginia",
  "western kentucky hilltoppers wku": "Western Kentucky",
  "western mich": "Western Michigan",
  "western michigan broncos wmu": "Western Michigan",
  "wis": "Wisconsin",
  "wisconsin badgers wis": "Wisconsin",
  "wiswisconsin": "Wisconsin",
  "wiswisconsin badgers": "Wisconsin",
  "wkuwestern kentucky": "Western Kentucky",
  "wkuwestern kentucky hilltoppers": "Western Kentucky",
  "wmu": "Western Michigan",
  "wmuwestern michigan": "Western Michigan",
  "wmuwestern michigan broncos": "Western Michigan",
  "wsu": "Washington State",
  "wsuwashington state": "Washington State",
  "wsuwashington state cougars": "Washington State",
  "wvu": "West Virginia",
  "wvuwest virginia": "West Virginia",
  "wvuwest virginia mountaineers": "West Virginia",
  "wyo": "Wyoming",
  "wyoming cowboys wyo": "Wyoming",
  "wyowyoming": "Wyoming",
  "wyowyoming cowboys": "Wyoming",
};

function normalize(name: string): string {
  return name
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "") // strip accents (José -> Jose)
    .toLowerCase()
    .replace(/[.'’]/g, "")
    // Pad "&" with spaces before converting to "and" — "A&T" (no
    // surrounding spaces in the raw text) and "A & T" both need to land
    // on the same normalized "a and t", or an alias keyed on one form
    // silently never matches the other.
    .replace(/&/g, " and ")
    .replace(/\s+/g, " ")
    .trim();
}

// Reverse index: normalized canonical name -> canonical name, so an exact
// (post-normalization) match against the real roster works even without an
// explicit alias entry.
const NORMALIZED_CANONICAL: Record<string, string> = Object.fromEntries(
  TEAMS.map((t) => [normalize(t.team), t.team])
);

// General abbreviation expansion — covers the many "X St" / "N/S/E/W/C
// ___" school names without hand-listing every single one in ALIASES.
// Trailing "st" -> "state" (Ohio St -> Ohio State); leading direction
// initials -> full word (N Illinois -> North Illinois, C Michigan ->
// Central Michigan). Only applied as a fallback after exact/alias checks.
function expandAbbrevs(norm: string): string {
  const words = norm.split(" ");
  return words
    .map((w, i) => {
      if (i === words.length - 1 && w === "st") return "state";
      if (i === 0 && w === "n") return "north";
      if (i === 0 && w === "s") return "south";
      if (i === 0 && w === "e") return "east";
      if (i === 0 && w === "w") return "west";
      if (i === 0 && w === "c") return "central";
      return w;
    })
    .join(" ");
}

function levenshtein(a: string, b: string): number {
  const dp: number[][] = Array.from({ length: a.length + 1 }, () => new Array(b.length + 1).fill(0));
  for (let i = 0; i <= a.length; i++) dp[i][0] = i;
  for (let j = 0; j <= b.length; j++) dp[0][j] = j;
  for (let i = 1; i <= a.length; i++) {
    for (let j = 1; j <= b.length; j++) {
      dp[i][j] =
        a[i - 1] === b[j - 1]
          ? dp[i - 1][j - 1]
          : 1 + Math.min(dp[i - 1][j - 1], dp[i - 1][j], dp[i][j - 1]);
    }
  }
  return dp[a.length][b.length];
}

export interface TeamMatchResult {
  input: string;
  matched: string | null; // canonical team name, or null if nothing close enough
  confidence: "exact" | "alias" | "fuzzy" | "none";
}

/** Best-effort match of an external source's team name onto this site's canonical roster. */
export function matchTeamName(input: string): TeamMatchResult {
  if (TEAMS_BY_NAME[input]) return { input, matched: input, confidence: "exact" };

  const norm = normalize(input);
  if (ALIASES[norm]) return { input, matched: ALIASES[norm], confidence: "alias" };
  if (NORMALIZED_CANONICAL[norm]) return { input, matched: NORMALIZED_CANONICAL[norm], confidence: "exact" };

  const expanded = expandAbbrevs(norm);
  if (expanded !== norm) {
    if (ALIASES[expanded]) return { input, matched: ALIASES[expanded], confidence: "alias" };
    if (NORMALIZED_CANONICAL[expanded]) return { input, matched: NORMALIZED_CANONICAL[expanded], confidence: "alias" };
  }

  // Fuzzy fallback — nearest canonical name by edit distance. Skipped
  // entirely for short names (< 6 characters after normalization):
  // college nickname/abbreviation soup is full of short strings that are
  // textually close but completely different schools (real cases hit
  // during testing: "ETSU" matched "LSU" at distance 2, "Cal" matched
  // "UAB" at distance 2) — for anything that short, distance-2 is not a
  // meaningful signal of similarity, so it's alias-or-nothing instead.
  // Longer names use a tighter ratio than before (15% of length, was
  // 20%) for the same reason at a smaller scale.
  if (norm.length < 6) {
    return { input, matched: null, confidence: "none" };
  }
  let best: { team: string; dist: number } | null = null;
  for (const t of TEAMS) {
    const d = levenshtein(norm, normalize(t.team));
    if (best == null || d < best.dist) best = { team: t.team, dist: d };
  }
  if (best && best.dist <= Math.max(1, Math.floor(norm.length * 0.15))) {
    return { input, matched: best.team, confidence: "fuzzy" };
  }
  return { input, matched: null, confidence: "none" };
}

// Several external feeds (Kalshi, The Odds API's exchange listings) give
// team names as "School Mascot" (e.g. "Ohio State Buckeyes") rather than
// just the school name our canonical roster uses. Try the string as-is
// first (matchTeamName already knows plenty of "School Mascot ABBR" forms
// from other sources), then progressively drop trailing words — the
// canonical name is almost always a strict prefix of the "School Mascot"
// form.
export function matchSchoolMascotName(input: string): string | null {
  let result = matchTeamName(input);
  if (result.matched) return result.matched;

  const words = input.split(" ");
  for (let cut = 1; cut <= 2 && words.length - cut >= 1; cut++) {
    result = matchTeamName(words.slice(0, words.length - cut).join(" "));
    if (result.matched) return result.matched;
  }
  return null;
}

export interface BulkMatchResult<T> {
  matched: { row: T; team: string; confidence: "exact" | "alias" | "fuzzy" }[];
  unmatched: T[];
}

/** Matches a batch of external rows against the canonical roster, given a way to pull the raw name out of each row. */
export function matchTeamRows<T>(rows: T[], nameOf: (row: T) => string): BulkMatchResult<T> {
  const matched: BulkMatchResult<T>["matched"] = [];
  const unmatched: T[] = [];
  for (const row of rows) {
    const result = matchTeamName(nameOf(row));
    if (result.matched) matched.push({ row, team: result.matched, confidence: result.confidence as any });
    else unmatched.push(row);
  }
  return { matched, unmatched };
}
