-- One-time seed: populates the `teams` table from the existing static data.
-- Run this once in the Supabase SQL editor, after schema.sql.
-- Re-running it is safe (it upserts on team name).

insert into teams (team, div, conf) values
  ('Ohio State', 'FBS', 'Big Ten'),
  ('Indiana', 'FBS', 'Big Ten'),
  ('Oregon', 'FBS', 'Big Ten'),
  ('Notre Dame', 'FBS', 'FBS Independents'),
  ('Texas Tech', 'FBS', 'Big 12'),
  ('Georgia', 'FBS', 'SEC'),
  ('Miami', 'FBS', 'ACC'),
  ('Alabama', 'FBS', 'SEC'),
  ('Texas', 'FBS', 'SEC'),
  ('Texas A&M', 'FBS', 'SEC'),
  ('Ole Miss', 'FBS', 'SEC'),
  ('Oklahoma', 'FBS', 'SEC'),
  ('USC', 'FBS', 'Big Ten'),
  ('Utah', 'FBS', 'Big 12'),
  ('Penn State', 'FBS', 'Big Ten'),
  ('Michigan', 'FBS', 'Big Ten'),
  ('BYU', 'FBS', 'Big 12'),
  ('Vanderbilt', 'FBS', 'SEC'),
  ('Iowa', 'FBS', 'Big Ten'),
  ('Tennessee', 'FBS', 'SEC'),
  ('Washington', 'FBS', 'Big Ten'),
  ('LSU', 'FBS', 'SEC'),
  ('Missouri', 'FBS', 'SEC'),
  ('SMU', 'FBS', 'ACC'),
  ('Auburn', 'FBS', 'SEC'),
  ('Louisville', 'FBS', 'ACC'),
  ('Clemson', 'FBS', 'ACC'),
  ('Illinois', 'FBS', 'Big Ten'),
  ('Arizona', 'FBS', 'Big 12'),
  ('Virginia', 'FBS', 'ACC'),
  ('TCU', 'FBS', 'Big 12'),
  ('Pittsburgh', 'FBS', 'ACC'),
  ('South Carolina', 'FBS', 'SEC'),
  ('Florida', 'FBS', 'SEC'),
  ('Kansas State', 'FBS', 'Big 12'),
  ('South Florida', 'FBS', 'American Athletic'),
  ('Florida State', 'FBS', 'ACC'),
  ('Iowa State', 'FBS', 'Big 12'),
  ('James Madison', 'FBS', 'Sun Belt'),
  ('Nebraska', 'FBS', 'Big Ten'),
  ('Georgia Tech', 'FBS', 'ACC'),
  ('Arizona State', 'FBS', 'Big 12'),
  ('North Texas', 'FBS', 'American Athletic'),
  ('Houston', 'FBS', 'Big 12'),
  ('Cincinnati', 'FBS', 'Big 12'),
  ('NC State', 'FBS', 'ACC'),
  ('Boise State', 'FBS', 'Pac-12'),
  ('Arkansas', 'FBS', 'SEC'),
  ('Duke', 'FBS', 'ACC'),
  ('Kansas', 'FBS', 'Big 12'),
  ('Tulane', 'FBS', 'American Athletic'),
  ('Kentucky', 'FBS', 'SEC'),
  ('Mississippi State', 'FBS', 'SEC'),
  ('Memphis', 'FBS', 'American Athletic'),
  ('Baylor', 'FBS', 'Big 12'),
  ('Minnesota', 'FBS', 'Big Ten'),
  ('Toledo', 'FBS', 'Mid-American'),
  ('Northwestern', 'FBS', 'Big Ten'),
  ('Wake Forest', 'FBS', 'ACC'),
  ('UNLV', 'FBS', 'Mountain West'),
  ('Navy', 'FBS', 'American Athletic'),
  ('Old Dominion', 'FBS', 'Sun Belt'),
  ('Rutgers', 'FBS', 'Big Ten'),
  ('North Dakota State', 'FBS', 'Mountain West'),
  ('East Carolina', 'FBS', 'American Athletic'),
  ('Wisconsin', 'FBS', 'Big Ten'),
  ('Washington State', 'FBS', 'Pac-12'),
  ('San Diego State', 'FBS', 'Pac-12'),
  ('Michigan State', 'FBS', 'Big Ten'),
  ('UCF', 'FBS', 'Big 12'),
  ('Maryland', 'FBS', 'Big Ten'),
  ('UTSA', 'FBS', 'American Athletic'),
  ('Virginia Tech', 'FBS', 'ACC'),
  ('Colorado', 'FBS', 'Big 12'),
  ('California', 'FBS', 'ACC'),
  ('West Virginia', 'FBS', 'Big 12'),
  ('UCLA', 'FBS', 'Big Ten'),
  ('New Mexico', 'FBS', 'Mountain West'),
  ('Army', 'FBS', 'American Athletic'),
  ('Fresno State', 'FBS', 'Pac-12'),
  ('Texas State', 'FBS', 'Pac-12'),
  ('UConn', 'FBS', 'FBS Independents'),
  ('Western Michigan', 'FBS', 'Mid-American'),
  ('North Carolina', 'FBS', 'ACC'),
  ('Hawai''i', 'FBS', 'Mountain West'),
  ('Purdue', 'FBS', 'Big Ten'),
  ('Ohio', 'FBS', 'Mid-American'),
  ('Utah State', 'FBS', 'Pac-12'),
  ('Montana State', 'FCS', 'Big Sky'),
  ('Boston College', 'FBS', 'ACC'),
  ('Miami (OH)', 'FBS', 'Mid-American'),
  ('Stanford', 'FBS', 'ACC'),
  ('Western Kentucky', 'FBS', 'Conference USA'),
  ('Air Force', 'FBS', 'Mountain West'),
  ('Syracuse', 'FBS', 'ACC'),
  ('Louisiana Tech', 'FBS', 'Sun Belt'),
  ('Troy', 'FBS', 'Sun Belt'),
  ('Liberty', 'FBS', 'Conference USA'),
  ('Jacksonville State', 'FBS', 'Conference USA'),
  ('Temple', 'FBS', 'American Athletic'),
  ('Marshall', 'FBS', 'Sun Belt'),
  ('Central Michigan', 'FBS', 'Mid-American'),
  ('Kennesaw State', 'FBS', 'Conference USA'),
  ('Louisiana', 'FBS', 'Sun Belt'),
  ('Florida International', 'FBS', 'Conference USA'),
  ('Southern Miss', 'FBS', 'Sun Belt'),
  ('Arkansas State', 'FBS', 'Sun Belt'),
  ('Montana', 'FCS', 'Big Sky'),
  ('Wyoming', 'FBS', 'Mountain West'),
  ('Oklahoma State', 'FBS', 'Big 12'),
  ('Tarleton State', 'FCS', 'UAC'),
  ('Georgia Southern', 'FBS', 'Sun Belt'),
  ('South Alabama', 'FBS', 'Sun Belt'),
  ('Oregon State', 'FBS', 'Pac-12'),
  ('Florida Atlantic', 'FBS', 'American Athletic'),
  ('Buffalo', 'FBS', 'Mid-American'),
  ('Missouri State', 'FBS', 'Conference USA'),
  ('San José State', 'FBS', 'Mountain West'),
  ('South Dakota State', 'FCS', 'MVFC'),
  ('App State', 'FBS', 'Sun Belt'),
  ('Bowling Green', 'FBS', 'Mid-American'),
  ('Eastern Michigan', 'FBS', 'Mid-American'),
  ('Colorado State', 'FBS', 'Pac-12'),
  ('Tulsa', 'FBS', 'American Athletic'),
  ('Coastal Carolina', 'FBS', 'Sun Belt'),
  ('Stephen F. Austin', 'FCS', 'Southland'),
  ('Delaware', 'FBS', 'Conference USA'),
  ('Nevada', 'FBS', 'Mountain West'),
  ('Lehigh', 'FCS', 'Patriot'),
  ('Northern Illinois', 'FBS', 'Mountain West'),
  ('UAB', 'FBS', 'American Athletic'),
  ('North Dakota', 'FCS', 'MVFC'),
  ('Rice', 'FBS', 'American Athletic'),
  ('Yale', 'FCS', 'Ivy'),
  ('New Mexico State', 'FBS', 'Conference USA'),
  ('Harvard', 'FCS', 'Ivy'),
  ('Akron', 'FBS', 'Mid-American'),
  ('UTEP', 'FBS', 'Mountain West'),
  ('Middle Tennessee', 'FBS', 'Conference USA'),
  ('Illinois State', 'FCS', 'MVFC'),
  ('UL Monroe', 'FBS', 'Sun Belt'),
  ('Georgia State', 'FBS', 'Sun Belt'),
  ('UC Davis', 'FCS', 'Big Sky'),
  ('Abilene Christian', 'FCS', 'UAC'),
  ('Southern Illinois', 'FCS', 'MVFC'),
  ('Villanova', 'FCS', 'CAA'),
  ('Ball State', 'FBS', 'Mid-American'),
  ('South Dakota', 'FCS', 'MVFC'),
  ('Mercer', 'FCS', 'Southern'),
  ('Kent State', 'FBS', 'Mid-American'),
  ('Sacramento State', 'FBS', 'Mid-American'),
  ('Rhode Island', 'FCS', 'CAA'),
  ('SE Louisiana', 'FCS', 'Southland'),
  ('Charlotte', 'FBS', 'American Athletic'),
  ('Austin Peay', 'FCS', 'UAC'),
  ('Southern Utah', 'FCS', 'UAC'),
  ('Dartmouth', 'FCS', 'Ivy'),
  ('Sam Houston', 'FBS', 'Conference USA'),
  ('Idaho State', 'FCS', 'Big Sky'),
  ('Youngstown State', 'FCS', 'MVFC'),
  ('Tennessee Tech', 'FCS', 'Big South-OVC'),
  ('South Carolina State', 'FCS', 'MEAC'),
  ('Monmouth', 'FCS', 'CAA'),
  ('Northern Arizona', 'FCS', 'Big Sky'),
  ('Jackson State', 'FCS', 'SWAC'),
  ('UT Rio Grande Valley', 'FCS', 'Southland'),
  ('Idaho', 'FCS', 'Big Sky'),
  ('Pennsylvania', 'FCS', 'Ivy'),
  ('Western Carolina', 'FCS', 'Southern'),
  ('St. Thomas (MN)', 'FCS', 'Pioneer'),
  ('Eastern Kentucky', 'FCS', 'UAC'),
  ('New Hampshire', 'FCS', 'CAA'),
  ('Incarnate Word', 'FCS', 'Southland'),
  ('West Georgia', 'FCS', 'UAC'),
  ('Gardner-Webb', 'FCS', 'Big South-OVC'),
  ('Drake', 'FCS', 'Pioneer'),
  ('North Carolina Central', 'FCS', 'MEAC'),
  ('Lafayette', 'FCS', 'Patriot'),
  ('Princeton', 'FCS', 'Ivy'),
  ('Presbyterian', 'FCS', 'Pioneer'),
  ('Lamar', 'FCS', 'Southland'),
  ('San Diego', 'FCS', 'Pioneer'),
  ('Stony Brook', 'FCS', 'CAA'),
  ('Brown', 'FCS', 'Ivy'),
  ('East Tennessee State', 'FCS', 'Southern'),
  ('Alabama State', 'FCS', 'SWAC'),
  ('Holy Cross', 'FCS', 'Patriot'),
  ('Cal Poly', 'FCS', 'Big Sky'),
  ('William & Mary', 'FCS', 'CAA'),
  ('UT Martin', 'FCS', 'Big South-OVC'),
  ('Massachusetts', 'FBS', 'Mid-American'),
  ('Cornell', 'FCS', 'Ivy'),
  ('Central Connecticut', 'FCS', 'NEC'),
  ('Eastern Washington', 'FCS', 'Big Sky'),
  ('Towson', 'FCS', 'CAA'),
  ('Wofford', 'FCS', 'Southern'),
  ('Maine', 'FCS', 'CAA'),
  ('Elon', 'FCS', 'CAA'),
  ('Northern Iowa', 'FCS', 'MVFC'),
  ('Lindenwood', 'FCS', 'Big South-OVC'),
  ('Richmond', 'FCS', 'Patriot'),
  ('Dayton', 'FCS', 'Pioneer'),
  ('Columbia', 'FCS', 'Ivy'),
  ('Duquesne', 'FCS', 'NEC'),
  ('Southeast Missouri State', 'FCS', 'Big South-OVC'),
  ('Nicholls', 'FCS', 'Southland'),
  ('Colgate', 'FCS', 'Patriot'),
  ('Prairie View A&M', 'FCS', 'SWAC'),
  ('Weber State', 'FCS', 'Big Sky'),
  ('Butler', 'FCS', 'Pioneer'),
  ('Georgetown', 'FCS', 'Patriot'),
  ('Central Arkansas', 'FCS', 'UAC'),
  ('Furman', 'FCS', 'Southern'),
  ('Indiana State', 'FCS', 'MVFC'),
  ('Chattanooga', 'FCS', 'Southern'),
  ('Sacred Heart', 'FCS', 'FCS Independents'),
  ('Delaware State', 'FCS', 'MEAC'),
  ('New Haven', 'FCS', 'NEC'),
  ('Long Island University', 'FCS', 'NEC'),
  ('McNeese', 'FCS', 'Southland'),
  ('Northern Colorado', 'FCS', 'Big Sky'),
  ('Marist', 'FCS', 'Pioneer'),
  ('The Citadel', 'FCS', 'Southern'),
  ('Charleston Southern', 'FCS', 'Big South-OVC'),
  ('Merrimack', 'FCS', 'FCS Independents'),
  ('UAlbany', 'FCS', 'CAA'),
  ('Utah Tech', 'FCS', 'UAC'),
  ('East Texas A&M', 'FCS', 'Southland'),
  ('Alabama A&M', 'FCS', 'SWAC'),
  ('Mercyhurst', 'FCS', 'NEC'),
  ('North Alabama', 'FCS', 'UAC'),
  ('Bryant', 'FCS', 'CAA'),
  ('Eastern Illinois', 'FCS', 'Big South-OVC'),
  ('Bucknell', 'FCS', 'Patriot'),
  ('Portland State', 'FCS', 'Big Sky'),
  ('Fordham', 'FCS', 'Patriot'),
  ('Morgan State', 'FCS', 'MEAC'),
  ('Alcorn State', 'FCS', 'SWAC'),
  ('Morehead State', 'FCS', 'Pioneer'),
  ('Western Illinois', 'FCS', 'Big South-OVC'),
  ('Texas Southern', 'FCS', 'SWAC'),
  ('Campbell', 'FCS', 'CAA'),
  ('Murray State', 'FCS', 'MVFC'),
  ('Hampton', 'FCS', 'CAA'),
  ('Bethune-Cookman', 'FCS', 'SWAC'),
  ('Howard', 'FCS', 'MEAC'),
  ('Florida A&M', 'FCS', 'SWAC'),
  ('St. Francis (PA)', 'FCS', 'NEC'),
  ('Robert Morris', 'FCS', 'NEC'),
  ('Grambling', 'FCS', 'SWAC'),
  ('Tennessee State', 'FCS', 'Big South-OVC'),
  ('Wagner', 'FCS', 'NEC'),
  ('Houston Christian', 'FCS', 'Southland'),
  ('Samford', 'FCS', 'Southern'),
  ('Stonehill', 'FCS', 'NEC'),
  ('Norfolk State', 'FCS', 'MEAC'),
  ('Valparaiso', 'FCS', 'Pioneer'),
  ('North Carolina A&T', 'FCS', 'CAA'),
  ('Davidson', 'FCS', 'Pioneer'),
  ('Southern', 'FCS', 'SWAC'),
  ('VMI', 'FCS', 'Southern'),
  ('Arkansas-Pine Bluff', 'FCS', 'SWAC'),
  ('Stetson', 'FCS', 'Pioneer'),
  ('Northwestern State', 'FCS', 'Southland'),
  ('Mississippi Valley State', 'FCS', 'SWAC')
on conflict (team) do update set div = excluded.div, conf = excluded.conf;
