-- Migration: add_advanced_stats_to_team_season_stats
-- Applied to Supabase project uyxnmtsntiaxqqmwsteq.
-- Adds CFBD /stats/season/advanced fields (PPA, success rate,
-- explosiveness, points per opportunity, havoc, line yards, stuff rate,
-- power success — overall, standard/passing downs, and rushing/passing
-- plays splits, for both offense and defense) to team_season_stats.
-- These feed the rewritten Game Totals engine (src/lib/gameTotals.ts).

alter table team_season_stats
  add column if not exists off_ppa numeric,
  add column if not exists off_success_rate numeric,
  add column if not exists off_explosiveness numeric,
  add column if not exists off_points_per_opportunity numeric,
  add column if not exists off_power_success numeric,
  add column if not exists off_stuff_rate numeric,
  add column if not exists off_line_yards numeric,
  add column if not exists off_standard_downs_ppa numeric,
  add column if not exists off_standard_downs_success_rate numeric,
  add column if not exists off_standard_downs_explosiveness numeric,
  add column if not exists off_passing_downs_ppa numeric,
  add column if not exists off_passing_downs_success_rate numeric,
  add column if not exists off_passing_downs_explosiveness numeric,
  add column if not exists off_rushing_plays_ppa numeric,
  add column if not exists off_rushing_plays_success_rate numeric,
  add column if not exists off_rushing_plays_explosiveness numeric,
  add column if not exists off_passing_plays_ppa numeric,
  add column if not exists off_passing_plays_success_rate numeric,
  add column if not exists off_passing_plays_explosiveness numeric,
  add column if not exists off_field_position_avg_start numeric,
  add column if not exists off_field_position_avg_predicted_points numeric,
  add column if not exists off_havoc_total numeric,
  add column if not exists off_havoc_front_seven numeric,
  add column if not exists off_havoc_db numeric,
  add column if not exists def_ppa numeric,
  add column if not exists def_success_rate numeric,
  add column if not exists def_explosiveness numeric,
  add column if not exists def_points_per_opportunity numeric,
  add column if not exists def_power_success numeric,
  add column if not exists def_stuff_rate numeric,
  add column if not exists def_line_yards numeric,
  add column if not exists def_standard_downs_ppa numeric,
  add column if not exists def_standard_downs_success_rate numeric,
  add column if not exists def_standard_downs_explosiveness numeric,
  add column if not exists def_passing_downs_ppa numeric,
  add column if not exists def_passing_downs_success_rate numeric,
  add column if not exists def_passing_downs_explosiveness numeric,
  add column if not exists def_rushing_plays_ppa numeric,
  add column if not exists def_rushing_plays_success_rate numeric,
  add column if not exists def_rushing_plays_explosiveness numeric,
  add column if not exists def_passing_plays_ppa numeric,
  add column if not exists def_passing_plays_success_rate numeric,
  add column if not exists def_passing_plays_explosiveness numeric,
  add column if not exists def_field_position_avg_start numeric,
  add column if not exists def_field_position_avg_predicted_points numeric,
  add column if not exists def_havoc_total numeric,
  add column if not exists def_havoc_front_seven numeric,
  add column if not exists def_havoc_db numeric;
